# Generated by Django 2.1.5 on 2019-01-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_current_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalpi',
            name='promote',
        ),
        migrations.RemoveField(
            model_name='groupdiscussionround',
            name='promote',
        ),
        migrations.RemoveField(
            model_name='taskroundone',
            name='promote',
        ),
        migrations.RemoveField(
            model_name='taskroundtwo',
            name='promote',
        ),
    ]
